name: Verificar secret

on:
  workflow_dispatch:

jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar existencia del secret
        env:
          API_KEY_DEMO: ${{ secrets.API_KEY_DEMO }}
        run: |
          if [ -z "$API_KEY_DEMO" ]; then
            echo "El secret API_KEY_DEMO no existe"
            exit 1
          else
            echo "El secret API_KEY_DEMO existe, pero no se imprimirá su valor por seguridad"
          fi